name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Save secrets to .env
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env

      - name: Create SSH key
        run: |
          echo "${{ secrets.KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
            # Pull code (if using git clone), or just copy files via SCP in real cases
            # Or, clone repo and build manually
            docker stop nextapp || true && docker rm nextapp || true
            docker rmi nextapp:latest || true

            cd ~/next-app
            git pull origin main
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env

            docker build -t nextapp .
            docker run -d --name nextapp -p 3000:3000 --env-file .env nextapp
          EOF
