name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Create .env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "PORT=3000" >> .env

      - name: Prepare directory on EC2
        run: |
          ssh ec2-user@${{ secrets.EC2_PUBLIC_IP }} "mkdir -p /home/ec2-user/deploy/nextjs-app"

      - name: Copy project files to EC2
        run: |
          rsync -avz --delete ./ ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user/deploy/nextjs-app

      - name: Deploy on EC2
        run: |
          ssh ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd /home/ec2-user/deploy/nextjs-app

            echo "DATABASE_URL=${DATABASE_URL}" > .env
            echo "PORT=3000" >> .env

            docker stop nextjs-app || true && docker rm nextjs-app || true
            docker rmi nextjs-app:latest || true

            docker build -t nextjs-app .

            docker network create simple-net || true

            docker run -d \
              --name nextjs-app \
              --network simple-net \
              --env-file .env \
              -p 3000:3000 \
              nextjs-app
          EOF
